export const vacancyList = [
        {
            "vacancyID": 1,
            "value": 0,
            "startDate": "2024-06-25T14:15:26.7311546",
            "endDate": "2024-07-25T14:15:26.7311797",
            "requirements": "Teste de vaga atual",
            "description": "Teste de vaga atual",
            "projectTitle": "Projeto teste de vaga",
            "status": "Aberta",
            "students": null,
            "professor": null,
            "professorID": 1,
            "vacancyType": null,
            "vacancyTypeID": 1
        },
        {
            "vacancyID": 2,
            "value": 0,
            "startDate": "2024-05-06T14:15:26.7311822",
            "endDate": "2024-06-15T14:15:26.7311825",
            "requirements": "Teste de vaga antiga",
            "description": "Teste de vaga antiga",
            "projectTitle": "Projeto teste de vaga",
            "status": "Fechada",
            "students": null,
            "professor": null,
            "professorID": 1,
            "vacancyType": null,
            "vacancyTypeID": 1
        },
        {
            "vacancyID": 3,
            "value": 1000,
            "startDate": "2024-06-25T14:15:26.7311834",
            "endDate": "2024-07-05T14:15:26.7311836",
            "requirements": "Conhecimento em Java",
            "description": "Desenvolvimento de aplicação web",
            "projectTitle": "Sistema de gerenciamento de vendas",
            "status": "Aberta",
            "students": null,
            "professor": null,
            "professorID": 2,
            "vacancyType": null,
            "vacancyTypeID": 1
        },
        {
            "vacancyID": 4,
            "value": 1000,
            "startDate": "2024-06-25T14:15:26.7311843",
            "endDate": "2024-08-04T14:15:26.7311844",
            "requirements": "Conhecimento em Java",
            "description": "Desenvolvimento de aplicação web",
            "projectTitle": "Sistema de gerenciamento de vendas",
            "status": "Aberta",
            "students": null,
            "professor": null,
            "professorID": 3,
            "vacancyType": null,
            "vacancyTypeID": 1
        },
        {
            "vacancyID": 5,
            "value": 1000,
            "startDate": "2024-06-15T14:15:26.7311851",
            "endDate": "2024-06-25T14:15:26.7311853",
            "requirements": "Conhecimento em Java",
            "description": "Desenvolvimento de aplicação web",
            "projectTitle": "Sistema de gerenciamento de vendas",
            "status": "Aberta",
            "students": null,
            "professor": null,
            "professorID": 4,
            "vacancyType": null,
            "vacancyTypeID": 2
        },
        {
            "vacancyID": 6,
            "value": 700,
            "startDate": "2024-06-15T14:15:26.731186",
            "endDate": "2024-07-25T14:15:26.7311862",
            "requirements": "Conhecimento em Java",
            "description": "Desenvolvimento de aplicação web",
            "projectTitle": "Sistema de gerenciamento de vendas",
            "status": "Aberta",
            "students": null,
            "professor": null,
            "professorID": 2,
            "vacancyType": null,
            "vacancyTypeID": 3
        },
        {
            "vacancyID": 7,
            "value": 0,
            "startDate": "2024-06-25T14:15:26.7311869",
            "endDate": "2024-08-04T14:15:26.7311871",
            "requirements": "Conhecimento em Java",
            "description": "Desenvolvimento de aplicação web",
            "projectTitle": "Sistema de gerenciamento de vendas",
            "status": "Aberta",
            "students": null,
            "professor": null,
            "professorID": 3,
            "vacancyType": null,
            "vacancyTypeID": 4
        },
        {
            "vacancyID": 8,
            "value": 1000,
            "startDate": "2024-06-25T14:15:26.7311976",
            "endDate": "2024-07-05T14:15:26.7311978",
            "requirements": "Conhecimento em Java",
            "description": "Desenvolvimento de aplicação web",
            "projectTitle": "Sistema de gerenciamento de vendas",
            "status": "Aberta",
            "students": null,
            "professor": null,
            "professorID": 4,
            "vacancyType": null,
            "vacancyTypeID": 5
        }
]